version: "3.8"

services:
### POSTGRES
  postgres:
      image: postgres:16.2-alpine3.19
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      networks:
        - backend

### KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin   
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8100/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      - start-dev
    volumes:
      - ./auth/import:/opt/keycloak/data/import
    ports:
      - "8100:8080"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres_data:
      driver: local